/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ["class"],
    content: [
        "./pages/**/*.{ts,tsx}",
        "./components/**/*.{ts,tsx}",
        "./app/**/*.{ts,tsx}",
        "./src/**/*.{ts,tsx}",
    ],
    theme: {
        container: {
            center: true,
            padding: "2rem",
            screens: {
                "2xl": "1400px",
            },
        },
        extend: {
            colors: {
                black: {
                    50: "#E9E7E7",
                    100: "#D6D1D2",
                    200: "#ABA0A3",
                    300: "#827377",
                    400: "#51484A",
                    500: "#231F20",
                    600: "#1B1819",
                    700: "#161314",
                    800: "#0E0C0C",
                    900: "#080707",
                    950: "#030202",
                },
                orange: {
                    50: "#FFEEE5",
                    100: "#FFDCCC",
                    200: "#FFB999",
                    300: "#FF9666",
                    400: "#FF7433",
                    500: "#FF5001",
                    600: "#CC4100",
                    700: "#993000",
                    800: "#662000",
                    900: "#331000",
                    950: "#190800",
                },
                white: {
                    50: "#FCFCFC",
                    100: "#FCFCFC",
                    200: "#F7F7F7",
                    300: "#F5F5F5",
                    400: "#F2F2F2",
                    500: "#EFEFEF",
                    600: "#BFBFBF",
                    700: "#8F8F8F",
                    800: "#5E5E5E",
                    900: "#303030",
                    950: "#171717",
                },
                silver: {
                    50: "#F8F7F7",
                    100: "#F1F0EF",
                    200: "#E0DEDC",
                    300: "#D2CFCB",
                    400: "#C1BDB8",
                    500: "#B3AEA8",
                    600: "#928A82",
                    700: "#706962",
                    800: "#494540",
                    900: "#262421",
                    950: "#131211",
                },
                gray: {
                    50: "#EFEFF0",
                    100: "#E0E0E1",
                    200: "#C1C0C3",
                    300: "#A2A1A5",
                    400: "#838288",
                    500: "#646368",
                    600: "#505054",
                    700: "#3C3C3F",
                    800: "#28282A",
                    900: "#141415",
                    950: "#0A0A0A",
                },
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                primary: {
                    DEFAULT: "hsl(var(--primary))",
                    foreground: "hsl(var(--primary-foreground))",
                },
                secondary: {
                    DEFAULT: "hsl(var(--secondary))",
                    foreground: "hsl(var(--secondary-foreground))",
                },
                destructive: {
                    DEFAULT: "hsl(var(--destructive))",
                    foreground: "hsl(var(--destructive-foreground))",
                },
                muted: {
                    DEFAULT: "hsl(var(--muted))",
                    foreground: "hsl(var(--muted-foreground))",
                },
                accent: {
                    DEFAULT: "hsl(var(--accent))",
                    foreground: "hsl(var(--accent-foreground))",
                },
                popover: {
                    DEFAULT: "hsl(var(--popover))",
                    foreground: "hsl(var(--popover-foreground))",
                },
                card: {
                    DEFAULT: "hsl(var(--card))",
                    foreground: "hsl(var(--card-foreground))",
                },
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
            },
            keyframes: {
                "accordion-down": {
                    from: { height: 0 },
                    to: { height: "var(--radix-accordion-content-height)" },
                },
                "accordion-up": {
                    from: { height: "var(--radix-accordion-content-height)" },
                    to: { height: 0 },
                },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
};
