/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ["class"],
    content: [
        "./pages/**/*.{ts,tsx}",
        "./components/**/*.{ts,tsx}",
        "./app/**/*.{ts,tsx}",
        "./src/**/*.{ts,tsx}",
    ],
    theme: {
        container: {
            center: true,
            padding: "2rem",
            screens: {
                "2xl": "1400px",
            },
        },
        extend: {
            colors: {
                smoke: {
                    50: "#E3E3E8",
                    100: "#CACAD3",
                    200: "#9494A8",
                    300: "#606076",
                    400: "#353541",
                    500: "#09090B",
                    600: "#070708",
                    700: "#050506",
                    800: "#050506",
                    900: "#020203",
                    950: "#000000",
                },
                green: {
                    50: "#E3FCF6",
                    100: "#C3F9EB",
                    200: "#86F3D8",
                    300: "#4AEDC4",
                    400: "#16DFAD",
                    500: "#10A37F",
                    600: "#0D8265",
                    700: "#0A624C",
                    800: "#064132",
                    900: "#032119",
                    950: "#02130E",
                },
                stone: {
                    50: "#E9EAEC",
                    100: "#D1D3D7",
                    200: "#A5A9B1",
                    300: "#777D88",
                    400: "#51555D",
                    500: "#282A2E",
                    600: "#212326",
                    700: "#18191B",
                    800: "#111113",
                    900: "#070708",
                    950: "#050505",
                },
                lightgreen: {
                    50: "#FBFEFD",
                    100: "#F8FCFB",
                    200: "#F1F9F7",
                    300: "#E9F6F3",
                    400: "#DEF2ED",
                    500: "#D8EFE9",
                    600: "#96D4C3",
                    700: "#59BBA1",
                    800: "#35826E",
                    900: "#1B4137",
                    950: "#0D211B",
                },
                yellow: {
                    50: "#FFFAF0",
                    100: "#FFF3DC",
                    200: "#FFE7B8",
                    300: "#FEDD9A",
                    400: "#FED176",
                    500: "#FEC553",
                    600: "#FEAF11",
                    700: "#CB8801",
                    800: "#845801",
                    900: "#422C00",
                    950: "#231800",
                },
                orange: {
                    50: "#FEF1F1",
                    100: "#FCE3E3",
                    200: "#FAC7C7",
                    300: "#F7ABAB",
                    400: "#F58F8F",
                    500: "#F27474",
                    600: "#EC3232",
                    700: "#C41212",
                    800: "#830C0C",
                    900: "#410606",
                    950: "#210303",
                },
                neutral: {
                    50: "#FFFFFF",
                    100: "#FCFCFC",
                    200: "#FAFAFA",
                    300: "#F7F7F7",
                    400: "#F7F7F7",
                    500: "#F4F4F4",
                    600: "#C4C4C4",
                    700: "#919191",
                    800: "#616161",
                    900: "#303030",
                    950: "#1A1A1A",
                },
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                primary: {
                    DEFAULT: "hsl(var(--primary))",
                    foreground: "hsl(var(--primary-foreground))",
                },
                secondary: {
                    DEFAULT: "hsl(var(--secondary))",
                    foreground: "hsl(var(--secondary-foreground))",
                },
                destructive: {
                    DEFAULT: "hsl(var(--destructive))",
                    foreground: "hsl(var(--destructive-foreground))",
                },
                muted: {
                    DEFAULT: "hsl(var(--muted))",
                    foreground: "hsl(var(--muted-foreground))",
                },
                accent: {
                    DEFAULT: "hsl(var(--accent))",
                    foreground: "hsl(var(--accent-foreground))",
                },
                popover: {
                    DEFAULT: "hsl(var(--popover))",
                    foreground: "hsl(var(--popover-foreground))",
                },
                card: {
                    DEFAULT: "hsl(var(--card))",
                    foreground: "hsl(var(--card-foreground))",
                },
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
            },
            keyframes: {
                "accordion-down": {
                    from: { height: 0 },
                    to: { height: "var(--radix-accordion-content-height)" },
                },
                "accordion-up": {
                    from: { height: "var(--radix-accordion-content-height)" },
                    to: { height: 0 },
                },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
};
