/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ["class"],
    content: [
        "./pages/**/*.{ts,tsx}",
        "./components/**/*.{ts,tsx}",
        "./app/**/*.{ts,tsx}",
        "./src/**/*.{ts,tsx}",
    ],
    theme: {
        container: {
            center: true,
            padding: "2rem",
            screens: {
                "2xl": "1400px",
            },
        },
        extend: {
            colors: {
                white: {
                    50: "#FFFFFF",
                    100: "#FFFFFF",
                    200: "#FFFFFF",
                    300: "#FEFCFB",
                    400: "#FEFCFB",
                    500: "#FEFCFB",
                    600: "#EABFA9",
                    700: "#D58258",
                    800: "#A35229",
                    900: "#522914",
                    950: "#29140A",
                },
                blue: {
                    50: "#E7E6FA",
                    100: "#D3D0F5",
                    200: "#A39EEB",
                    300: "#776FE1",
                    400: "#4B41D8",
                    500: "#3026B9",
                    600: "#261E94",
                    700: "#1C176E",
                    800: "#130F48",
                    900: "#0A0826",
                    950: "#040311",
                },
                black: {
                    50: "#E6E6E6",
                    100: "#CCCCCC",
                    200: "#999999",
                    300: "#666666",
                    400: "#333333",
                    500: "#000000",
                    600: "#000000",
                    700: "#000000",
                    800: "#000000",
                    900: "#000000",
                    950: "#000000",
                },
                polygreen: {
                    50: "#E3F2E5",
                    100: "#CBE7CE",
                    200: "#93CD99",
                    300: "#5EB568",
                    400: "#3E8847",
                    500: "#26532B",
                    600: "#1E4223",
                    700: "#16311A",
                    800: "#0E1F10",
                    900: "#081109",
                    950: "#030704",
                },
                ruby: {
                    50: "#FFE5ED",
                    100: "#FFD1DE",
                    200: "#FF9EBA",
                    300: "#FF7099",
                    400: "#FF3D74",
                    500: "#FF1053",
                    600: "#D6003D",
                    700: "#A3002E",
                    800: "#6B001E",
                    900: "#380010",
                    950: "#190007",
                },
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                primary: {
                    DEFAULT: "hsl(var(--primary))",
                    foreground: "hsl(var(--primary-foreground))",
                },
                secondary: {
                    DEFAULT: "hsl(var(--secondary))",
                    foreground: "hsl(var(--secondary-foreground))",
                },
                destructive: {
                    DEFAULT: "hsl(var(--destructive))",
                    foreground: "hsl(var(--destructive-foreground))",
                },
                muted: {
                    DEFAULT: "hsl(var(--muted))",
                    foreground: "hsl(var(--muted-foreground))",
                },
                accent: {
                    DEFAULT: "hsl(var(--accent))",
                    foreground: "hsl(var(--accent-foreground))",
                },
                popover: {
                    DEFAULT: "hsl(var(--popover))",
                    foreground: "hsl(var(--popover-foreground))",
                },
                card: {
                    DEFAULT: "hsl(var(--card))",
                    foreground: "hsl(var(--card-foreground))",
                },
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
            },
            keyframes: {
                "accordion-down": {
                    from: { height: 0 },
                    to: { height: "var(--radix-accordion-content-height)" },
                },
                "accordion-up": {
                    from: { height: "var(--radix-accordion-content-height)" },
                    to: { height: 0 },
                },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
};
